language: php

php:
  - 5.5.9

script:
  # Run your tests here.
  - echo 'Tested'

before_deploy:
  - mkdir build
  - cp LICENSE build
  - cp README.txt build
  - cp remove-medium-cross-links.php build

deploy:
  - provider: wordpress-plugin
    
    on:
      php: 5.5.9
      repo: guide
    username: ch12jan1998@gmail.com
    password: MyPassword
    build_dir: build
